Clean up filenames so they follow a common naming pattern, and with a suffix that will make them be ignored.

diff --git a/test/src/morphology/generate-verb-lemmas.sh.in b/test/src/morphology/generate-verb-lemmas.sh.in
--- a/test/src/morphology/generate-verb-lemmas.sh.in
+++ b/test/src/morphology/generate-verb-lemmas.sh.in
@@ -9,7 +9,7 @@
 
 # To run this test script only, do:
 #
-# make check TESTS=generate-noun-lemmas.sh
+# make check TESTS=generate-adjective-lemmas.sh
 
 # This test script will test that all noun lemmas do generate as themselves.
 # Extend as needed, and copy to new files to adapt to other parts of speech.
@@ -19,21 +19,19 @@
 # 2. extend the extract lemmas egrep expression (lines 53 ff)
 # 3. adapt the tag addition and lemma generation instructions (lines 79 ff)
 
+
 ###### Variables: #######
-POS=smn-propernouns
+POS=verbs
 ### in ###
-source_file=./../../../src/morphology/generated_files/smi-${POS}.lexc
+source_file=${srcdir}/../../../src/morphology/stems/${POS}.lexc
 generator_file=./../../../src/generator-gt-norm
-analyser_file=./../../../src/analyser-gt-norm
 
 ### out ###
 # Temporary files:
 lemmas=./filtered-${POS}.txt
 # Final files, will get filename suffix programmatically further down:
 generated_lemmas=./generated-${POS}
-result_file=missing_${POS}_lemmas
-gen_result_file=generated_missing_${POS}_lemmas
-ana_result_file=analysed_missing_${POS}_lemmas
+result_file=${srcdir}/missing_${POS}_lemmas
 
 # SKIP if source file does not exist (works with both single and
 # multiple files):
@@ -59,12 +57,21 @@ fi
 # Get external Mac editor for viewing failed results from configure:
 EXTEDITOR=@SEE@
 
+###### Extraction: #######
+
+#grep ";" $source_file | \
+#  egrep -v "^(\!|\@|<)" | grep -v '\+Neg' | \
+#  sed 's/% /€/g' | sed 's/%:/¢/g' |  tr ":+" " " | cut -d " " -f1 | \
+#  tr -d "%" | tr "€" " " | tr "¢" ":" | sort -u > $lemmas
+  
+
 ##### Extract lemmas - add additional egrep pattern as parameters: #####
 ##### --include "(pattern1|pattern2|...)"                          #####
 ##### --exclude "(pattern1|pattern2|...)"                          #####
 @GTCORE@/scripts/extract-lemmas.sh \
-  --exclude '(FirstTag|Proper_infix)' \
+    --exclude "( LE | IJ |ij\+V)" \
     $source_file > $lemmas
+
 
 ###### Start testing: #######
 transducer_found=0
@@ -93,69 +100,44 @@ for f in $fsttype; do
     if [ -f "$generator_file.$suffix" ]; then
         let "transducer_found += 1"
 
-###### Test non-comopunds: #######
-        # generate propers in singular, extract the resulting generated lemma,
-        # store it:
-        sed 's/$/+N+Prop+Sg+Nom/' $lemmas \
-			| $lookup_tool $generator_file.$suffix \
-			| fgrep -v "+?" | grep -v "^$" | cut -f2 \
-            > $generated_lemmas.$f.txt
+###### Generate the infinitives: #######
 
-        # Generate nouns, extract those that do not generate in singular,
-        # and try to generate them in plural:
-        sed 's/$/+N+Prop+Sg+Nom/' $lemmas \
-			| $lookup_tool $generator_file.$suffix \
-			| fgrep "+?" | cut -d "+" -f1 \
-			| sed 's/$/+N+Prop+Pl+Nom/' \
-			| $lookup_tool $generator_file.$suffix \
-			| fgrep -v "+?" | grep -v "^$" | cut -f2 \
-			>> $generated_lemmas.$f.txt
+        sed 's/$/+V+Inf/' $lemmas | \
+        		$lookup_tool $generator_file.$suffix | \
+          cut -f2 | grep -v "V+" | grep -v "^$" | sort -u > $generated_lemmas.$f.txt		
+				
+# Sorter, unifiser
+		sort -u -o $lemmas $lemmas 
+		sort -u -o $generated_lemmas.$f.txt $generated_lemmas.$f.txt 
 
-###### Collect results, and generate debug info if FAIL: #######
-        # Sort and compare original input with resulting output - the diff is
-        # used to generate lemmas which are opened in SEE:
-        sort -u -o $generated_lemmas.$f.txt $generated_lemmas.$f.txt 
-        comm -23 $lemmas $generated_lemmas.$f.txt > $result_file.$f.txt
+# Sammenlikne: Former som er i lemmalista med ikke i lista med genererte former,
+# lagre i missingverbLemmas.txt. Formene generes med  +V+Inf for enklere debugging.
+		comm -23 $lemmas $generated_lemmas.$f.txt |\
+		  grep -v '^$' | sed 's/$/+V+Inf/' |\
+		  $lookup_tool $generator_file.$suffix > $result_file.$f.txt
 
-        # Open the diff file in SubEthaEdit (if there is a diff):
-        if [ -s $result_file.$f.txt ]; then
-            grep -v '^$' $result_file.$f.txt \
-              | sed 's/$/+N+Prop+Sg+Nom/' \
-              | $lookup_tool $generator_file.$suffix \
-              > $gen_result_file.$f.txt
-            # If we have an analyser, analyse the missing lemmas as well:
-            if test -e $analyser_file.$suffix ; then
-                grep -v '^$' $result_file.$f.txt \
-                  | $lookup_tool $analyser_file.$suffix \
-                  > $ana_result_file.$f.txt
-            fi
-            # Only open the failed lemmas in see if @SEE@ is defined:
-            if [ "$EXTEDITOR" ]; then
-#                $EXTEDITOR $result_file.$f.txt
-                $EXTEDITOR $gen_result_file.$f.txt
-#                $EXTEDITOR $ana_result_file.$f.txt
-            else
-                echo "There where problem lemmas. Details in:"
-                echo "* $result_file.$f.txt    "
-                echo "* $gen_result_file.$f.txt"
-                echo "* $ana_result_file.$f.txt"
-            fi
-            Fail=1
-            echo "$f - FAIL"
-            continue
-        fi
-        echo "$f - PASS"
-    fi
+		# Open the diff file in SubEthaEdit (if there is a diff):
+		if [ -s $result_file.$f.txt ]; then
+			# Only open the failed lemmas in see if @SEE@ is defined:
+			if [ "$EXTEDITOR" ]; then
+				$EXTEDITOR $result_file.$f.txt
+			fi
+		    Fail=1
+		    echo "$f - FAIL"
+		    continue
+		fi
+	    echo "$f - PASS"
+	fi
 done
 
 # At least one of the Xerox or HFST tests failed:
 if [ "$Fail" = "1" ]; then
-    exit 1
+	exit 1
 fi
 
 if [ $transducer_found -eq 0 ]; then
     echo ERROR: No transducer found
-    exit 77
+    exit 1
 fi
 
 # When done, remove the generated data file:
