[Template merge] typofux

diff --git a/src/fst/morphology/test/generate-noun-lemmas.sh.in b/src/fst/morphology/test/generate-noun-lemmas.sh.in
--- a/src/fst/morphology/test/generate-noun-lemmas.sh.in
+++ b/src/fst/morphology/test/generate-noun-lemmas.sh.in
@@ -9,8 +9,11 @@ analyser_file=@abs_builddir@/../../analyser-gt-norm
 tags="+N+Sg+Nom"
 # advanced settings (leave empty or write full args)
 xtags="-t +N+Pl+Nom"
-inclusions=
-exclusions="--exclude (ShCmp|RCmpnd|COLL|\+CmpNP\/Suff|\+Use\/MT)"
+# {in,ex}clusions are given in arrays to retain spaces, for example:
+# inclusions=("--include" "REG EX" "--include" "EGERG XEX")
+inclusions=()
+exclusions=("--exclude" "(ShCmp|RCmpnd|COLL|\+CmpNP\/Suff|\+Use\/MT)")
+
 # avoid changing common scripting stuff here:
 
 . "$GIELLA_CORE/scripts/termcolors.bash"
@@ -42,10 +45,16 @@ if ! test -f "$source_file" ; then
         "$source_file"
     exit 1
 fi
+if ! test -f "$source_file" ; then
+    printf "%sfail%s missing lexc file %s\n" "$red" "$reset" \
+        "$source_file"
+    exit 1
+fi
 
 "$genscript" -l "$source_file" \
     -g "$generator_file.hfstol" -a "$analyser_file.hfstol" \
-    -t "$tags" $xtags $inclusions $exclusions
+    -t "$tags" $xtags "${inclusions[@]}" "${exclusions[@]}" \
+    -E @LOG_VIEWER@ 
 rv=$?
 if test $rv = 77 ; then
     printf "%sskipped%s\n" "$light_blue" "$reset"
