[Template merge] python generate lemmas

diff --git a/src/fst/morphology/test/generate-adjective-lemmas.sh.in b/src/fst/morphology/test/generate-adjective-lemmas.sh.in
--- a/src/fst/morphology/test/generate-adjective-lemmas.sh.in
+++ b/src/fst/morphology/test/generate-adjective-lemmas.sh.in
@@ -1,191 +1,59 @@
 #!/bin/bash
-# @configure_input@
-
-# Automake interprets the exit status as follows:
-# - an exit status of 0 will denote a success
-# - an exit status of 77 a skipped test
-# - an exit status of 99 a hard error
-# - any other exit status will denote a failure.
-
-# To run this test script only, do:
+# Test script for adjective lemma generation
 #
-# make check TESTS=generate-adjective-lemmas.sh
+# change settings here:
 
-# This test script will test that all adjective lemmas do generate as themselves.
-# Extend as needed, and copy to new files to adapt to other parts of speech.
-# The changes usually needed are:
-#
-# 1. change the reference to the source file (line 23)
-# 2. extend the extract lemmas egrep expression (lines 53 ff)
-# 3. adapt the tag addition and lemma generation instructions (lines 79 ff)
-
-###### Variables: #######
 POS=adjectives
-### in ###
-source_file=${srcdir}/../stems/${POS}.lexc
-generator_file=./../../generator-gt-norm
-analyser_file=./../../analyser-gt-norm
+source_file=@abs_srcdir@/../stems/${POS}.lexc
+generator_file=@abs_builddir@/../../generator-gt-norm
+analyser_file=@abs_builddir@/../../analyser-gt-norm
+tags="+A+Sg+Nom"
+# advanced settings (leave empty or write full args)
+xtags="-t +A+Attr -t +A+Superl+Sg+Nom -t +A+Comp+Sg+Nom"
+inclusions=
+exclusions=
 
-### out ###
-# Temporary files:
-lemmas=./filtered-${POS}.txt
-suplemmas=./superlative-${POS}.txt
-complemmas=./comperative-${POS}.txt
-attrlemmas=./attribute-${POS}.txt
-alllemmas=./all_lemma-${POS}.txt
-# Final files, will get filename suffix programmatically further down:
-generated_lemmas=./generated-${POS}
-result_file=missing_${POS}_lemmas
-gen_result_file=generated_missing_${POS}_lemmas
-ana_result_file=analysed_missing_${POS}_lemmas
+# avoid changing common scripting stuff here:
 
-# SKIP if source file does not exist (works with both single and
-# multiple files):
-if [ ! `ls -1 $source_file 2>/dev/null | wc -l ` -gt 0 ]; then
-    echo
-    echo "*** Warning: Source file(s) $source_file not found."
-    echo
-    exit 77
+. "$GIELLA_CORE/scripts/termcolors.bash"
+PYTHON=@PYTHON@
+genscript=$GIELLA_CORE/scripts/generate-lemmas.py
+
+# ensure this is proper run from make check or otherwise set up
+if test -z "$srcdir" ; then
+    printf "%sfail%s %s needs to run from make check or set srcdir=.\n" "$0" \
+        "$red" "$reset"
+    exit 1
 fi
-
-# Use autotools mechanisms to only run the configured fst types in the tests:
-fsttype=
-@CAN_HFST_TRUE@fsttype="$fsttype hfst"
-@CAN_XFST_TRUE@fsttype="$fsttype xfst"
-
-# Exit if both hfst and xerox have been shut off:
-if test -z "$fsttype" ; then
-    echo "All transducer types have been shut off at configure time."
-    echo "Nothing to test. Skipping."
-    exit 77
+if ! test -f "$genscript" ; then
+    printf "%sfail%s missing generator script %s\n" "$red" "$reset" \
+        "$genscript"
+    exit 1
 fi
-
-# Get external Mac editor for viewing failed results from configure:
-EXTEDITOR=@SEE@
-
-##### Extract lemmas #####
-# @GTCORE@/scripts/extract-lemmas.sh \
-#   --exclude '(pattern)' \
-#   --include '(pattern)' \
-# 	$sourcefile > $lemmas
-#
-# Hent ut lemmaer fra adjective.lexc, bortsett fra utkommmenterte (^\!), 
-# dem som krever sammensetning (CmpN/Only|ShCmp|RCmpnd| Rreal | R | Rnoun),
-# Lemmaene lagres som filtered-adjectives
-
-# Skriptet fjernar alltid desse, dvs at ein treng ikkje spesifisera dei:
-# (LEXICON| K |ENDLEX|\+Err\/Lex|DerSub)
-
-@GTCORE@/scripts/extract-lemmas.sh \
-  --exclude '(CmpN/Only|ShCmp|RCmpnd| Rreal | R | SUP|COMP | Rnoun |\+V\+|\+Use\/MT)' \
-    $source_file > $lemmas
-
-@GTCORE@/scripts/extract-lemmas.sh \
-  --include ' SUP' \
-  --exclude '(CmpN/Only|ShCmp|RCmpnd| Rreal | R | Rnoun |\+V\+)' \
-    $source_file > $suplemmas
-
-@GTCORE@/scripts/extract-lemmas.sh \
-  --include 'COMP ' \
-  --exclude '(CmpN/Only|ShCmp|RCmpnd| Rreal | R | Rnoun |\+V\+)' \
-    $source_file > $complemmas
-
-@GTCORE@/scripts/extract-lemmas.sh \
-  --include ' ATTR' \
-  --exclude '(CmpN/Only|ShCmp|RCmpnd| Rreal | R | Rnoun |\+V\+)' \
-    $source_file > $attrlemmas
-
-
-###### Start testing: #######
-transducer_found=0
-Fail=0
-
-# The script tests both Xerox and Hfst transducers if available:
-for f in $fsttype; do
-    if [ $f == "xfst" ]; then
-        lookup_tool="@LOOKUP@ -flags mbTT"
-        suffix="xfst"
-        # Does lookup support -q / quiet mode?
-        lookup_quiet=$($lookup_tool -q 2>&1 | grep USAGES)
-        if ! [[ $lookup_quiet == *"USAGES"* ]] ; then
-            # it does support quiet mode, add the -q flag:
-            lookup_tool="@LOOKUP@ -q -flags mbTT"
-        fi
-    elif [ $f == "hfst" ]; then
-        lookup_tool="@HFST_OPTIMIZED_LOOKUP@ -q"
-        suffix="hfstol"
-    else
-        Fail=1
-        printf "ERROR: Unknown fst type! "
-        echo "$f - FAIL"
-        continue
-    fi
-    if [ -f "$generator_file.$suffix" ]; then
-        let "transducer_found += 1"
-
-###### Test non-compounds: #######
-		# generate nouns in Singular, extract the resulting generated lemma,
-		# store it:
-# Generer lemmaer i adjectives med +A+Sg+Nom, lagre i generated-adjectives
-        sed 's/$/+A+Sg+Nom/' $lemmas | $lookup_tool $generator_file.$suffix | \
-          cut -f2 | grep -v "A+" | grep -v "^$" | sort -u > $generated_lemmas.$f.txt		
-
-# Generer lemmaer i adjectives med +A+Der/Superl+Sg+Nom, lagre i generated-adjectives
-        sed 's/$/+A+Der\/Superl+A+Sg+Nom/' $suplemmas | $lookup_tool $generator_file.$suffix | \
-          cut -f2 | grep -v "A+" | grep -v "^$" | sort -u >> $generated_lemmas.$f.txt		
-
-# Generer lemmaer i adjectives med +A+Der/Comp+Sg+Nom, lagre i generated-adjectives
-        sed 's/$/+A+Der\/Comp+A+Sg+Nom/' $complemmas | $lookup_tool $generator_file.$suffix | \
-          cut -f2 | grep -v "A+" | grep -v "^$" | sort -u >> $generated_lemmas.$f.txt		
-
-
-# Generer lemmaer i adjectives med +A+Attr, lagre i generated-adjectives
-        sed 's/$/+A+Attr/' $attrlemmas | $lookup_tool $generator_file.$suffix | \
-          cut -f2 | grep -v "A+" | grep -v "^$" | sort -u >> $generated_lemmas.$f.txt		
-
-		
-
-###### Collect results: #######
-		# Sort and compare original input with resulting output - the diff is
-		# stored and opened in SEE:
-
-# Sorter, unifiser
-        cat $lemmas $attrlemmas $suplemmas $complemmas  > $alllemmas
-		LC_ALL=no_NO.UTF-8 sort -u -o $alllemmas $alllemmas 
-		LC_ALL=no_NO.UTF-8 sort -u -o $generated_lemmas.$f.txt $generated_lemmas.$f.txt 
-
-# Sammenlikne: Former som er i lemmalista med ikke i lista med genererte former,
-# lagre i missing_adjective_lemmas.{FST}.txt. Formene generes med  +A+Sg+Nom for enklere debugging.
-		LC_ALL=no_NO.UTF-8 comm -23 $alllemmas $generated_lemmas.$f.txt |\
-		grep -v '^$' | sed 's/$/+A+Sg+Nom/' |\
-		$lookup_tool $generator_file.$suffix > $result_file.$f.txt
-
-		# Open the diff file in SubEthaEdit (if there is a diff):
-		if [ -s $result_file.$f.txt ]; then
-			# Only open the failed lemmas in see if @SEE@ is defined:
-			if [ "$EXTEDITOR" ]; then
-				$EXTEDITOR $result_file.$f.txt &
-            else
-                echo "There were problem lemmas. Details in:"
-                echo "* $result_file.$f.txt    "
-			fi
-		    Fail=1
-		    echo "$f - FAIL"
-		    continue
-		fi
-	    echo "$f - PASS"
-	fi
-done
-
-# At least one of the Xerox or HFST tests failed:
-if [ "$Fail" = "1" ]; then
+if ! test -f "$generator_file.hfstol" ; then
+    printf "%sfail%s missing generator FSA %s.hfstol\n" "$red" "$reset" \
+        "$generator_file"
+    exit 1
+fi
+if ! test -f "$analyser_file.hfstol" ; then
+    printf "%sfail%s missing analyser FSA %s.hfstol\n" "$red" "$reset" \
+        "$analyser_file"
+    exit 1
+fi
+if ! test -f "$source_file" ; then
+    printf "%sfail%s missing lexc file %s\n" "$red" "$reset" \
+        "$source_file"
     exit 1
 fi
 
-if [ $transducer_found -eq 0 ]; then
-    echo ERROR: No transducer found $analyser_file $generator_file
+"$PYTHON" -- "$genscript" -l "$source_file" \
+    -g "$generator_file.hfstol" -a "$analyser_file.hfstol" \
+    -t "$tags" $xtags $inclusions $exclusions
+rv=$?
+if test $rv = 77 ; then
+    printf "%sskipped%s\n" "$light_blue" "$reset"
     exit 77
+elif test $rv -gt 0 ; then
+    printf "%sfailed%s\n" "$red" "$reset"
+    exit 1
 fi
-
-# When done, remove the generated data file:
-rm -f $lemmas $attrlemmas $suplemmas $complemmas $alllemmas
